CREATE TABLE capacity_v1_contracts (
 id UUID PRIMARY KEY,schema_name TEXT NOT NULL CHECK(schema_name='family-capacity-contract-v1'),state TEXT NOT NULL CHECK(state='completed'),family TEXT NOT NULL CHECK(family IN ('passive_control','quality_filtered_wheel','momentum_quality','etf_time_series_trend','defined_risk_options')),
 evaluation_id UUID NOT NULL,evaluation_sha256 TEXT NOT NULL CHECK(evaluation_sha256~'^[0-9a-f]{64}$'),source_report_id UUID NOT NULL,source_report_sha256 TEXT NOT NULL CHECK(source_report_sha256~'^[0-9a-f]{64}$'),evaluation_start TIMESTAMPTZ NOT NULL,evaluation_end TIMESTAMPTZ NOT NULL CHECK(evaluation_end>evaluation_start),after_cost_return TEXT NOT NULL CHECK(evaluation_decimal_valid(after_cost_return)),capacity_available BOOLEAN NOT NULL,unavailable_reason TEXT NOT NULL,capital_per_unit TEXT NOT NULL CHECK(evaluation_decimal_valid(capital_per_unit)),maximum_units INTEGER NOT NULL CHECK(maximum_units>=0),
 sha256 TEXT NOT NULL CHECK(sha256~'^[0-9a-f]{64}$'),canonical_bytes BYTEA NOT NULL,canonical_json JSONB NOT NULL,created_at TIMESTAMPTZ NOT NULL,
 CHECK(sha256=encode(digest(canonical_bytes,'sha256'),'hex')),CHECK(canonical_json=convert_from(canonical_bytes,'UTF8')::JSONB),CHECK(id=economic_deterministic_uuid('family-capacity-contract',schema_name||'@sha256:'||sha256)),
 CHECK((capacity_available AND unavailable_reason='' AND capital_per_unit::NUMERIC>0 AND maximum_units>0) OR (NOT capacity_available AND unavailable_reason='source_capacity_not_observed' AND capital_per_unit::NUMERIC=0 AND maximum_units=0))
);
CREATE TABLE capacity_v1_comparisons (
 id UUID PRIMARY KEY,schema_name TEXT NOT NULL CHECK(schema_name='capital-tier-comparison-v1'),state TEXT NOT NULL CHECK(state='completed'),capital_policy_version TEXT NOT NULL,family_count INTEGER NOT NULL CHECK(family_count=5),sha256 TEXT NOT NULL CHECK(sha256~'^[0-9a-f]{64}$'),canonical_bytes BYTEA NOT NULL,canonical_json JSONB NOT NULL,created_at TIMESTAMPTZ NOT NULL,
 CHECK(sha256=encode(digest(canonical_bytes,'sha256'),'hex')),CHECK(canonical_json=convert_from(canonical_bytes,'UTF8')::JSONB),CHECK(id=economic_deterministic_uuid('capital-tier-comparison',schema_name||'@sha256:'||sha256))
);
CREATE TABLE capacity_v1_families (
 comparison_id UUID NOT NULL REFERENCES capacity_v1_comparisons(id) ON DELETE RESTRICT,sequence INTEGER NOT NULL CHECK(sequence BETWEEN 0 AND 4),family TEXT NOT NULL,contract_id UUID NOT NULL REFERENCES capacity_v1_contracts(id) ON DELETE RESTRICT,contract_sha256 TEXT NOT NULL,minimum_viable_tier TEXT NOT NULL,minimum_viable_available BOOLEAN NOT NULL,tier_count INTEGER NOT NULL CHECK(tier_count=6),canonical_family JSONB NOT NULL,PRIMARY KEY(comparison_id,sequence),UNIQUE(comparison_id,family),UNIQUE(comparison_id,contract_id)
);
CREATE TABLE capacity_v1_tiers (
 comparison_id UUID NOT NULL,family_sequence INTEGER NOT NULL,ordinal INTEGER NOT NULL CHECK(ordinal BETWEEN 0 AND 5),tier TEXT NOT NULL CHECK(tier IN ('500','5000','25000','100000','1000000','5000000')),viable BOOLEAN NOT NULL,reason TEXT NOT NULL,units INTEGER NOT NULL CHECK(units>=0),executable_capital TEXT NOT NULL CHECK(evaluation_decimal_valid(executable_capital) AND executable_capital::NUMERIC>=0),unused_capital TEXT NOT NULL CHECK(evaluation_decimal_valid(unused_capital) AND unused_capital::NUMERIC>=0),saturated BOOLEAN NOT NULL,canonical_tier JSONB NOT NULL,PRIMARY KEY(comparison_id,family_sequence,ordinal),FOREIGN KEY(comparison_id,family_sequence) REFERENCES capacity_v1_families(comparison_id,sequence) ON DELETE RESTRICT
);
CREATE FUNCTION validate_capacity_v1_comparison() RETURNS TRIGGER AS $$ DECLARE target UUID;comparison capacity_v1_comparisons%ROWTYPE;BEGIN target:=COALESCE((to_jsonb(NEW)->>'id')::UUID,(to_jsonb(NEW)->>'comparison_id')::UUID);SELECT * INTO comparison FROM capacity_v1_comparisons WHERE id=target;IF comparison.family_count<>(SELECT count(*) FROM capacity_v1_families WHERE comparison_id=target) OR comparison.canonical_json->'families'<>COALESCE((SELECT jsonb_agg(f.canonical_family ORDER BY f.sequence) FROM capacity_v1_families f WHERE f.comparison_id=target),'[]'::JSONB) OR EXISTS(SELECT 1 FROM capacity_v1_families f JOIN capacity_v1_contracts c ON c.id=f.contract_id WHERE f.comparison_id=target AND (f.contract_sha256<>c.sha256 OR f.family<>c.family OR f.tier_count<>(SELECT count(*) FROM capacity_v1_tiers t WHERE t.comparison_id=target AND t.family_sequence=f.sequence) OR f.canonical_family->'tiers'<>COALESCE((SELECT jsonb_agg(t.canonical_tier ORDER BY t.ordinal) FROM capacity_v1_tiers t WHERE t.comparison_id=target AND t.family_sequence=f.sequence),'[]'::JSONB))) THEN RAISE EXCEPTION 'capacity comparison graph does not reconstruct';END IF;RETURN NULL;END;$$ LANGUAGE plpgsql;
CREATE FUNCTION reject_capacity_v1_mutation() RETURNS TRIGGER AS $$ BEGIN RAISE EXCEPTION 'capacity v1 evidence is append-only';END;$$ LANGUAGE plpgsql;
DO $$ DECLARE n TEXT;BEGIN FOREACH n IN ARRAY ARRAY['capacity_v1_contracts','capacity_v1_comparisons','capacity_v1_families','capacity_v1_tiers'] LOOP EXECUTE format('CREATE TRIGGER %I BEFORE UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION reject_capacity_v1_mutation()','trg_'||n||'_immutable',n);END LOOP;END$$;
CREATE CONSTRAINT TRIGGER trg_capacity_v1_comparison_graph AFTER INSERT ON capacity_v1_comparisons DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION validate_capacity_v1_comparison();
CREATE CONSTRAINT TRIGGER trg_capacity_v1_family_graph AFTER INSERT ON capacity_v1_families DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION validate_capacity_v1_comparison();
CREATE CONSTRAINT TRIGGER trg_capacity_v1_tier_graph AFTER INSERT ON capacity_v1_tiers DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION validate_capacity_v1_comparison();
CREATE INDEX idx_capacity_v1_contracts_family ON capacity_v1_contracts(family,created_at,id);
