LOCK TABLE research_hypotheses,research_critics,promotion_policy_artifacts,promotion_retirement_decisions,strategy_deployments,statistical_robustness_assessments,strategy_versions IN SHARE ROW EXCLUSIVE MODE;

CREATE TABLE evidence_review_cases(
 id UUID PRIMARY KEY,schema_name TEXT NOT NULL CHECK(schema_name='evidence-review-case-v1'),state TEXT NOT NULL CHECK(state='open'),
 hypothesis_id UUID NOT NULL REFERENCES research_hypotheses(id),hypothesis_sha256 TEXT NOT NULL CHECK(hypothesis_sha256~'^[0-9a-f]{64}$'),
 critic_id UUID NOT NULL REFERENCES research_critics(id),critic_sha256 TEXT NOT NULL CHECK(critic_sha256~'^[0-9a-f]{64}$'),critic_recommendation TEXT NOT NULL CHECK(critic_recommendation IN('revise','reject','ready_for_experiment_review')),
 version_id UUID NOT NULL REFERENCES strategy_versions(id),version_sha256 TEXT NOT NULL CHECK(version_sha256~'^[0-9a-f]{64}$'),
 promotion_policy_id UUID NOT NULL REFERENCES promotion_policy_artifacts(id),promotion_policy_sha256 TEXT NOT NULL CHECK(promotion_policy_sha256~'^[0-9a-f]{64}$'),
 promotion_decision_id UUID NOT NULL REFERENCES promotion_retirement_decisions(id),promotion_decision_sha256 TEXT NOT NULL CHECK(promotion_decision_sha256~'^[0-9a-f]{64}$'),
 deployment_id UUID NOT NULL REFERENCES strategy_deployments(id),deployment_sha256 TEXT NOT NULL CHECK(deployment_sha256~'^[0-9a-f]{64}$'),
 assessment_id UUID NOT NULL REFERENCES statistical_robustness_assessments(id),assessment_sha256 TEXT NOT NULL CHECK(assessment_sha256~'^[0-9a-f]{64}$'),
 authoritative_outcome TEXT NOT NULL CHECK(authoritative_outcome IN('approved','held','retired')),authoritative_next_state TEXT NOT NULL,
 reference_count INT NOT NULL CHECK(reference_count>0),sha256 TEXT NOT NULL CHECK(sha256~'^[0-9a-f]{64}$'),canonical_bytes BYTEA NOT NULL,canonical_json JSONB NOT NULL CHECK(jsonb_typeof(canonical_json)='object'),created_at TIMESTAMPTZ NOT NULL DEFAULT date_trunc('microseconds',NOW()),
 CHECK(sha256=encode(digest(canonical_bytes,'sha256'),'hex')),CHECK(canonical_json=convert_from(canonical_bytes,'UTF8')::jsonb),CHECK(id=economic_deterministic_uuid('evidence-review-case',schema_name||'@sha256:'||sha256)),UNIQUE(hypothesis_id,critic_id,promotion_decision_id)
);
CREATE TABLE evidence_review_case_references(case_id UUID NOT NULL REFERENCES evidence_review_cases(id),sequence INT NOT NULL CHECK(sequence>=0),reference TEXT NOT NULL,PRIMARY KEY(case_id,sequence),UNIQUE(case_id,reference));
CREATE TABLE evidence_reviews(
 id UUID PRIMARY KEY,schema_name TEXT NOT NULL CHECK(schema_name='evidence-review-v1'),state TEXT NOT NULL CHECK(state='completed'),case_id UUID NOT NULL REFERENCES evidence_review_cases(id),case_sha256 TEXT NOT NULL CHECK(case_sha256~'^[0-9a-f]{64}$'),
 reviewer_key TEXT NOT NULL CHECK(reviewer_key~'^[a-z][a-z0-9_-]{0,95}$'),reviewer_kind TEXT NOT NULL CHECK(reviewer_kind IN('human','independent_service')),reviewer_identity_sha256 TEXT NOT NULL CHECK(reviewer_identity_sha256~'^[0-9a-f]{64}$'),reviewed_at TIMESTAMPTZ NOT NULL CHECK(reviewed_at=date_trunc('microseconds',reviewed_at)),
 prior_review_id UUID REFERENCES evidence_reviews(id),prior_review_sha256 TEXT NOT NULL DEFAULT '' CHECK(prior_review_sha256='' OR prior_review_sha256~'^[0-9a-f]{64}$'),check_count INT NOT NULL CHECK(check_count=6),disposition TEXT NOT NULL CHECK(disposition IN('evidence_supported','changes_requested','reject_evidence')),
 authoritative_outcome TEXT NOT NULL CHECK(authoritative_outcome IN('approved','held','retired')),authoritative_next_state TEXT NOT NULL,sha256 TEXT NOT NULL CHECK(sha256~'^[0-9a-f]{64}$'),canonical_bytes BYTEA NOT NULL,canonical_json JSONB NOT NULL CHECK(jsonb_typeof(canonical_json)='object'),created_at TIMESTAMPTZ NOT NULL DEFAULT date_trunc('microseconds',NOW()),
 CHECK(sha256=encode(digest(canonical_bytes,'sha256'),'hex')),CHECK(canonical_json=convert_from(canonical_bytes,'UTF8')::jsonb),CHECK(id=economic_deterministic_uuid('evidence-review',schema_name||'@sha256:'||sha256)),UNIQUE(prior_review_id)
);
CREATE UNIQUE INDEX idx_evidence_review_initial_reviewer ON evidence_reviews(case_id,reviewer_key) WHERE prior_review_id IS NULL;
CREATE TABLE evidence_review_checks(review_id UUID NOT NULL REFERENCES evidence_reviews(id),sequence INT NOT NULL CHECK(sequence>=0),check_name TEXT NOT NULL CHECK(check_name IN('cost_capacity','policy_decision_consistency','reproducibility','safety_boundaries','source_integrity','statistical_controls')),severity TEXT NOT NULL CHECK(severity IN('high','critical')),check_state TEXT NOT NULL CHECK(check_state IN('pass','fail','unknown')),canonical_row JSONB NOT NULL CHECK(jsonb_typeof(canonical_row)='object'),PRIMARY KEY(review_id,sequence),UNIQUE(review_id,check_name));
CREATE TABLE evidence_review_check_references(review_id UUID NOT NULL,check_sequence INT NOT NULL,sequence INT NOT NULL CHECK(sequence>=0),reference TEXT NOT NULL,PRIMARY KEY(review_id,check_sequence,sequence),UNIQUE(review_id,check_sequence,reference),FOREIGN KEY(review_id,check_sequence) REFERENCES evidence_review_checks(review_id,sequence));
CREATE TABLE evidence_review_summaries(
 id UUID PRIMARY KEY,schema_name TEXT NOT NULL CHECK(schema_name='evidence-review-summary-v1'),state TEXT NOT NULL CHECK(state='completed'),case_id UUID NOT NULL REFERENCES evidence_review_cases(id),case_sha256 TEXT NOT NULL CHECK(case_sha256~'^[0-9a-f]{64}$'),review_head_count INT NOT NULL CHECK(review_head_count BETWEEN 2 AND 32),check_count INT NOT NULL CHECK(check_count=6),consensus TEXT NOT NULL CHECK(consensus IN('evidence_supported','changes_requested','reject_evidence','disagreement')),escalation_required BOOLEAN NOT NULL,authoritative_outcome TEXT NOT NULL CHECK(authoritative_outcome IN('approved','held','retired')),authoritative_next_state TEXT NOT NULL,sha256 TEXT NOT NULL CHECK(sha256~'^[0-9a-f]{64}$'),canonical_bytes BYTEA NOT NULL,canonical_json JSONB NOT NULL CHECK(jsonb_typeof(canonical_json)='object'),created_at TIMESTAMPTZ NOT NULL DEFAULT date_trunc('microseconds',NOW()),
 CHECK(sha256=encode(digest(canonical_bytes,'sha256'),'hex')),CHECK(canonical_json=convert_from(canonical_bytes,'UTF8')::jsonb),CHECK(id=economic_deterministic_uuid('evidence-review-summary',schema_name||'@sha256:'||sha256)),UNIQUE(case_id,sha256)
);
CREATE TABLE evidence_review_summary_heads(summary_id UUID NOT NULL REFERENCES evidence_review_summaries(id),sequence INT NOT NULL CHECK(sequence>=0),review_id UUID NOT NULL REFERENCES evidence_reviews(id),review_sha256 TEXT NOT NULL CHECK(review_sha256~'^[0-9a-f]{64}$'),reviewer_key TEXT NOT NULL,canonical_row JSONB NOT NULL CHECK(jsonb_typeof(canonical_row)='object'),PRIMARY KEY(summary_id,sequence),UNIQUE(summary_id,review_id),UNIQUE(summary_id,reviewer_key));
CREATE TABLE evidence_review_summary_checks(summary_id UUID NOT NULL REFERENCES evidence_review_summaries(id),sequence INT NOT NULL CHECK(sequence>=0),check_name TEXT NOT NULL,canonical_row JSONB NOT NULL CHECK(jsonb_typeof(canonical_row)='object'),PRIMARY KEY(summary_id,sequence),UNIQUE(summary_id,check_name));

CREATE FUNCTION validate_evidence_review_case() RETURNS TRIGGER AS $$ DECLARE target UUID;c evidence_review_cases%ROWTYPE;BEGIN target:=COALESCE((to_jsonb(NEW)->>'id')::uuid,(to_jsonb(NEW)->>'case_id')::uuid);SELECT * INTO c FROM evidence_review_cases WHERE id=target;IF c.id IS NULL OR c.hypothesis_sha256<>(SELECT sha256 FROM research_hypotheses WHERE id=c.hypothesis_id) OR c.critic_sha256<>(SELECT sha256 FROM research_critics WHERE id=c.critic_id) OR c.version_sha256<>(SELECT sha256 FROM strategy_versions WHERE id=c.version_id) OR c.promotion_policy_sha256<>(SELECT sha256 FROM promotion_policy_artifacts WHERE id=c.promotion_policy_id) OR c.promotion_decision_sha256<>(SELECT sha256 FROM promotion_retirement_decisions WHERE id=c.promotion_decision_id) OR c.deployment_sha256<>(SELECT sha256 FROM strategy_deployments WHERE id=c.deployment_id) OR c.assessment_sha256<>(SELECT sha256 FROM statistical_robustness_assessments WHERE id=c.assessment_id) OR c.canonical_json->>'schema'<>c.schema_name OR c.canonical_json->>'state'<>c.state OR c.canonical_json->>'authoritative_outcome'<>c.authoritative_outcome OR c.canonical_json->>'authoritative_next_state'<>c.authoritative_next_state OR c.reference_count<>jsonb_array_length(c.canonical_json->'evidence_references') OR c.reference_count<>(SELECT count(*) FROM evidence_review_case_references WHERE case_id=c.id) OR EXISTS(SELECT 1 FROM evidence_review_case_references r WHERE r.case_id=c.id AND to_jsonb(r.reference)<>c.canonical_json->'evidence_references'->r.sequence) THEN RAISE EXCEPTION 'evidence review case does not reconstruct';END IF;RETURN NULL;END;$$ LANGUAGE plpgsql;
CREATE FUNCTION validate_evidence_review() RETURNS TRIGGER AS $$ DECLARE target UUID;r evidence_reviews%ROWTYPE;c evidence_review_cases%ROWTYPE;BEGIN target:=COALESCE((to_jsonb(NEW)->>'id')::uuid,(to_jsonb(NEW)->>'review_id')::uuid);SELECT * INTO r FROM evidence_reviews WHERE id=target;SELECT * INTO c FROM evidence_review_cases WHERE id=r.case_id;IF r.id IS NULL OR r.case_sha256<>c.sha256 OR r.canonical_json->>'schema'<>r.schema_name OR r.canonical_json->>'state'<>r.state OR r.canonical_json->>'case_id'<>r.case_id::text OR r.canonical_json->>'case_sha256'<>r.case_sha256 OR r.canonical_json->'reviewer'->>'key'<>r.reviewer_key OR r.canonical_json->'reviewer'->>'kind'<>r.reviewer_kind OR r.canonical_json->'reviewer'->>'identity_sha256'<>r.reviewer_identity_sha256 OR r.canonical_json->>'disposition'<>r.disposition OR r.authoritative_outcome<>c.authoritative_outcome OR r.authoritative_next_state<>c.authoritative_next_state OR r.check_count<>jsonb_array_length(r.canonical_json->'checks') OR r.check_count<>(SELECT count(*) FROM evidence_review_checks WHERE review_id=r.id) OR EXISTS(SELECT 1 FROM evidence_review_checks k WHERE k.review_id=r.id AND(k.canonical_row<>r.canonical_json->'checks'->k.sequence OR jsonb_array_length(k.canonical_row->'references')<>(SELECT count(*) FROM evidence_review_check_references x WHERE x.review_id=r.id AND x.check_sequence=k.sequence) OR EXISTS(SELECT 1 FROM evidence_review_check_references x WHERE x.review_id=r.id AND x.check_sequence=k.sequence AND to_jsonb(x.reference)<>k.canonical_row->'references'->x.sequence))) OR r.prior_review_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM evidence_reviews p WHERE p.id=r.prior_review_id AND p.sha256=r.prior_review_sha256 AND p.case_id=r.case_id AND p.reviewer_key=r.reviewer_key AND p.reviewed_at<r.reviewed_at) THEN RAISE EXCEPTION 'evidence review does not reconstruct';END IF;RETURN NULL;END;$$ LANGUAGE plpgsql;
CREATE FUNCTION validate_evidence_review_summary() RETURNS TRIGGER AS $$ DECLARE target UUID;s evidence_review_summaries%ROWTYPE;c evidence_review_cases%ROWTYPE;BEGIN target:=COALESCE((to_jsonb(NEW)->>'id')::uuid,(to_jsonb(NEW)->>'summary_id')::uuid);SELECT * INTO s FROM evidence_review_summaries WHERE id=target;SELECT * INTO c FROM evidence_review_cases WHERE id=s.case_id;IF s.id IS NULL OR s.case_sha256<>c.sha256 OR s.canonical_json->>'schema'<>s.schema_name OR s.canonical_json->>'state'<>s.state OR s.canonical_json->>'consensus'<>s.consensus OR(s.canonical_json->>'escalation_required')::boolean<>s.escalation_required OR s.authoritative_outcome<>c.authoritative_outcome OR s.authoritative_next_state<>c.authoritative_next_state OR s.review_head_count<>(SELECT count(*) FROM evidence_review_summary_heads WHERE summary_id=s.id) OR s.check_count<>(SELECT count(*) FROM evidence_review_summary_checks WHERE summary_id=s.id) OR EXISTS(SELECT 1 FROM evidence_review_summary_heads h JOIN evidence_reviews r ON r.id=h.review_id WHERE h.summary_id=s.id AND(h.review_sha256<>r.sha256 OR r.case_id<>s.case_id OR h.canonical_row<>s.canonical_json->'review_heads'->h.sequence)) OR EXISTS(SELECT 1 FROM evidence_review_summary_checks k WHERE k.summary_id=s.id AND k.canonical_row<>s.canonical_json->'checks'->k.sequence) THEN RAISE EXCEPTION 'evidence review summary does not reconstruct';END IF;RETURN NULL;END;$$ LANGUAGE plpgsql;
CREATE FUNCTION validate_evidence_review_authority() RETURNS TRIGGER AS $$
DECLARE expected TEXT; parent RECORD;
BEGIN
 IF TG_TABLE_NAME='evidence_review_cases' THEN
  SELECT d.outcome,d.next_state,d.version_id,d.deployment_id,d.assessment_id,d.policy_id INTO parent FROM promotion_retirement_decisions d WHERE d.id=NEW.promotion_decision_id;
  IF NEW.canonical_json->>'hypothesis_id'<>NEW.hypothesis_id::TEXT OR NEW.canonical_json->>'critic_id'<>NEW.critic_id::TEXT OR NEW.canonical_json->>'critic_recommendation'<>NEW.critic_recommendation OR NEW.canonical_json->>'version_id'<>NEW.version_id::TEXT OR NEW.canonical_json->>'promotion_policy_id'<>NEW.promotion_policy_id::TEXT OR NEW.canonical_json->>'promotion_decision_id'<>NEW.promotion_decision_id::TEXT OR NEW.canonical_json->>'deployment_id'<>NEW.deployment_id::TEXT OR NEW.canonical_json->>'assessment_id'<>NEW.assessment_id::TEXT OR parent.outcome<>NEW.authoritative_outcome OR parent.next_state<>NEW.authoritative_next_state OR parent.version_id<>NEW.version_id OR parent.deployment_id<>NEW.deployment_id OR parent.assessment_id<>NEW.assessment_id OR parent.policy_id<>NEW.promotion_policy_id THEN RAISE EXCEPTION 'evidence review authority binding does not reconstruct';END IF;
 ELSIF TG_TABLE_NAME='evidence_reviews' THEN
  expected:=CASE WHEN EXISTS(SELECT 1 FROM jsonb_array_elements(NEW.canonical_json->'checks') x WHERE x->>'severity'='critical' AND x->>'state'='fail') THEN 'reject_evidence' WHEN EXISTS(SELECT 1 FROM jsonb_array_elements(NEW.canonical_json->'checks') x WHERE x->>'state'<>'pass') THEN 'changes_requested' ELSE 'evidence_supported' END;
  IF expected<>NEW.disposition OR NEW.canonical_json->>'authoritative_outcome'<>NEW.authoritative_outcome OR NEW.canonical_json->>'authoritative_next_state'<>NEW.authoritative_next_state THEN RAISE EXCEPTION 'evidence review disposition does not reconstruct';END IF;
 ELSE
  SELECT CASE WHEN min(x->>'disposition')=max(x->>'disposition') THEN min(x->>'disposition') ELSE 'disagreement' END INTO expected FROM jsonb_array_elements(NEW.canonical_json->'review_heads') x;
  IF expected<>NEW.consensus OR NEW.escalation_required<>(expected<>'evidence_supported' OR EXISTS(SELECT 1 FROM jsonb_array_elements(NEW.canonical_json->'checks') x WHERE (x->>'fail_count')::INT>0 OR (x->>'unknown_count')::INT>0)) OR NEW.canonical_json->>'authoritative_outcome'<>NEW.authoritative_outcome OR NEW.canonical_json->>'authoritative_next_state'<>NEW.authoritative_next_state THEN RAISE EXCEPTION 'evidence review summary authority does not reconstruct';END IF;
 END IF;RETURN NEW;
END;$$ LANGUAGE plpgsql;
CREATE TRIGGER trg_evidence_review_case_authority BEFORE INSERT ON evidence_review_cases FOR EACH ROW EXECUTE FUNCTION validate_evidence_review_authority();
CREATE TRIGGER trg_evidence_review_authority BEFORE INSERT ON evidence_reviews FOR EACH ROW EXECUTE FUNCTION validate_evidence_review_authority();
CREATE TRIGGER trg_evidence_review_summary_authority BEFORE INSERT ON evidence_review_summaries FOR EACH ROW EXECUTE FUNCTION validate_evidence_review_authority();
CREATE FUNCTION reject_evidence_review_mutation() RETURNS TRIGGER AS $$BEGIN RAISE EXCEPTION 'evidence review is append-only';END;$$ LANGUAGE plpgsql;
DO $$DECLARE name TEXT;BEGIN FOREACH name IN ARRAY ARRAY['evidence_review_cases','evidence_review_case_references','evidence_reviews','evidence_review_checks','evidence_review_check_references','evidence_review_summaries','evidence_review_summary_heads','evidence_review_summary_checks'] LOOP EXECUTE format('CREATE TRIGGER %I BEFORE UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION reject_evidence_review_mutation()','trg_'||name||'_immutable',name);END LOOP;END$$;
CREATE CONSTRAINT TRIGGER trg_evidence_review_case AFTER INSERT ON evidence_review_cases DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION validate_evidence_review_case();CREATE CONSTRAINT TRIGGER trg_evidence_review_case_ref AFTER INSERT ON evidence_review_case_references DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION validate_evidence_review_case();
CREATE CONSTRAINT TRIGGER trg_evidence_review AFTER INSERT ON evidence_reviews DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION validate_evidence_review();CREATE CONSTRAINT TRIGGER trg_evidence_review_check AFTER INSERT ON evidence_review_checks DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION validate_evidence_review();CREATE CONSTRAINT TRIGGER trg_evidence_review_check_ref AFTER INSERT ON evidence_review_check_references DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION validate_evidence_review();
CREATE CONSTRAINT TRIGGER trg_evidence_review_summary AFTER INSERT ON evidence_review_summaries DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION validate_evidence_review_summary();CREATE CONSTRAINT TRIGGER trg_evidence_review_summary_head AFTER INSERT ON evidence_review_summary_heads DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION validate_evidence_review_summary();CREATE CONSTRAINT TRIGGER trg_evidence_review_summary_check AFTER INSERT ON evidence_review_summary_checks DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION validate_evidence_review_summary();
CREATE INDEX idx_evidence_review_cases_version ON evidence_review_cases(version_id,created_at,id);CREATE INDEX idx_evidence_reviews_case ON evidence_reviews(case_id,reviewer_key,reviewed_at,id);
