-- OVR-702 append-only local shadow-campaign evidence. No scheduling,
-- provider, allocation, deployment, account, risk, or execution authority.
CREATE TABLE shadow_campaigns(
 id UUID PRIMARY KEY,schema_name TEXT NOT NULL CHECK(schema_name='shadow-campaign-v1'),campaign_key TEXT NOT NULL UNIQUE,started_at TIMESTAMPTZ NOT NULL CHECK(started_at=date_trunc('day',started_at)),target_days INT NOT NULL CHECK(target_days=30),
 benchmark_id UUID NOT NULL REFERENCES benchmark_opportunity_cost_reports(id),benchmark_sha256 TEXT NOT NULL CHECK(benchmark_sha256~'^[0-9a-f]{64}$'),candidate_count INT NOT NULL CHECK(candidate_count BETWEEN 2 AND 16),sha256 TEXT NOT NULL CHECK(sha256~'^[0-9a-f]{64}$'),canonical_bytes BYTEA NOT NULL,canonical_json JSONB NOT NULL CHECK(jsonb_typeof(canonical_json)='object'),created_at TIMESTAMPTZ NOT NULL DEFAULT date_trunc('microseconds',clock_timestamp()),
 CHECK(sha256=encode(digest(canonical_bytes,'sha256'),'hex')),CHECK(canonical_json=convert_from(canonical_bytes,'UTF8')::JSONB),CHECK(id=economic_deterministic_uuid('shadow-campaign',schema_name||'@sha256:'||sha256))
);
CREATE TABLE shadow_campaign_candidates(campaign_id UUID NOT NULL REFERENCES shadow_campaigns(id),sequence INT NOT NULL CHECK(sequence BETWEEN 0 AND 15),candidate_key TEXT NOT NULL,version_id UUID NOT NULL REFERENCES strategy_versions(id),version_sha256 TEXT NOT NULL CHECK(version_sha256~'^[0-9a-f]{64}$'),canonical_row JSONB NOT NULL CHECK(jsonb_typeof(canonical_row)='object'),PRIMARY KEY(campaign_id,sequence),UNIQUE(campaign_id,candidate_key),UNIQUE(campaign_id,version_id));
CREATE TABLE shadow_campaign_days(
 id UUID PRIMARY KEY,schema_name TEXT NOT NULL CHECK(schema_name='shadow-campaign-day-v1'),campaign_id UUID NOT NULL REFERENCES shadow_campaigns(id),campaign_sha256 TEXT NOT NULL CHECK(campaign_sha256~'^[0-9a-f]{64}$'),sequence INT NOT NULL CHECK(sequence BETWEEN 0 AND 29),observed_at TIMESTAMPTZ NOT NULL CHECK(observed_at=date_trunc('day',observed_at)),source_kind TEXT NOT NULL,source_id UUID NOT NULL,source_sha256 TEXT NOT NULL CHECK(source_sha256~'^[0-9a-f]{64}$'),candidate_count INT NOT NULL CHECK(candidate_count BETWEEN 2 AND 16),sha256 TEXT NOT NULL CHECK(sha256~'^[0-9a-f]{64}$'),canonical_bytes BYTEA NOT NULL,canonical_json JSONB NOT NULL CHECK(jsonb_typeof(canonical_json)='object'),created_at TIMESTAMPTZ NOT NULL DEFAULT date_trunc('microseconds',clock_timestamp()),
 UNIQUE(campaign_id,sequence),CHECK(sha256=encode(digest(canonical_bytes,'sha256'),'hex')),CHECK(canonical_json=convert_from(canonical_bytes,'UTF8')::JSONB),CHECK(id=economic_deterministic_uuid('shadow-campaign-day',schema_name||'@sha256:'||sha256))
);
CREATE TABLE shadow_campaign_day_candidates(day_id UUID NOT NULL REFERENCES shadow_campaign_days(id),sequence INT NOT NULL CHECK(sequence BETWEEN 0 AND 15),candidate_key TEXT NOT NULL,critical_defects INT NOT NULL CHECK(critical_defects>=0),executable_samples INT NOT NULL CHECK(executable_samples>=0),simulated_fills INT NOT NULL CHECK(simulated_fills>=0),slippage_known BOOLEAN NOT NULL,slippage_divergence TEXT NOT NULL,CHECK((slippage_known AND evaluation_decimal_valid(slippage_divergence)) OR (NOT slippage_known AND slippage_divergence='')),canonical_row JSONB NOT NULL CHECK(jsonb_typeof(canonical_row)='object'),PRIMARY KEY(day_id,sequence),UNIQUE(day_id,candidate_key));

CREATE FUNCTION reject_shadow_campaign_mutation() RETURNS TRIGGER AS $$BEGIN RAISE EXCEPTION 'shadow campaign evidence is append-only';END;$$ LANGUAGE plpgsql;
CREATE FUNCTION validate_shadow_campaign_graph() RETURNS TRIGGER AS $$
DECLARE target UUID;c shadow_campaigns%ROWTYPE;d shadow_campaign_days%ROWTYPE;
BEGIN
 IF TG_TABLE_NAME='shadow_campaigns' THEN target:=NEW.id;ELSIF TG_TABLE_NAME='shadow_campaign_candidates' THEN target:=NEW.campaign_id;ELSE target:=NULL;END IF;
 IF target IS NOT NULL THEN
  SELECT * INTO c FROM shadow_campaigns WHERE id=target;
  IF c.candidate_count<>(SELECT count(*) FROM shadow_campaign_candidates WHERE campaign_id=c.id) OR c.benchmark_sha256<>(SELECT sha256 FROM benchmark_opportunity_cost_reports WHERE id=c.benchmark_id) OR c.canonical_json->>'schema'<>c.schema_name OR c.canonical_json->>'key'<>c.campaign_key OR (c.canonical_json->>'target_days')::INT<>30 OR c.canonical_json->>'started_at'<>to_char(c.started_at AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"') OR c.canonical_json->'benchmark'<>jsonb_build_object('kind','benchmark_opportunity_cost_report','id',c.benchmark_id::TEXT,'sha256',c.benchmark_sha256) OR c.canonical_json->'candidates'<>(SELECT jsonb_agg(x.canonical_row ORDER BY x.sequence) FROM shadow_campaign_candidates x WHERE x.campaign_id=c.id) OR EXISTS(SELECT 1 FROM shadow_campaign_candidates x JOIN strategy_versions v ON v.id=x.version_id WHERE x.campaign_id=c.id AND x.version_sha256<>v.sha256) THEN RAISE EXCEPTION 'shadow campaign graph does not reconstruct';END IF;
 ELSE
  IF TG_TABLE_NAME='shadow_campaign_days' THEN target:=NEW.id;ELSE target:=NEW.day_id;END IF;SELECT * INTO d FROM shadow_campaign_days WHERE id=target;SELECT * INTO c FROM shadow_campaigns WHERE id=d.campaign_id;
  IF d.campaign_sha256<>c.sha256 OR d.observed_at<>c.started_at+d.sequence*INTERVAL '1 day' OR d.candidate_count<>(SELECT count(*) FROM shadow_campaign_day_candidates WHERE day_id=d.id) OR d.candidate_count<>c.candidate_count OR d.canonical_json->>'schema'<>d.schema_name OR d.canonical_json->>'campaign_id'<>d.campaign_id::TEXT OR d.canonical_json->>'campaign_sha256'<>d.campaign_sha256 OR (d.canonical_json->>'sequence')::INT<>d.sequence OR d.canonical_json->>'observed_at'<>to_char(d.observed_at AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"') OR d.canonical_json->'source'<>jsonb_build_object('kind',d.source_kind,'id',d.source_id::TEXT,'sha256',d.source_sha256) OR d.canonical_json->'candidates'<>(SELECT jsonb_agg(x.canonical_row ORDER BY x.sequence) FROM shadow_campaign_day_candidates x WHERE x.day_id=d.id) OR EXISTS(SELECT 1 FROM shadow_campaign_candidates expected WHERE expected.campaign_id=c.id AND NOT EXISTS(SELECT 1 FROM shadow_campaign_day_candidates actual WHERE actual.day_id=d.id AND actual.candidate_key=expected.candidate_key)) OR EXISTS(SELECT 1 FROM shadow_campaign_day_candidates actual WHERE actual.day_id=d.id AND NOT EXISTS(SELECT 1 FROM shadow_campaign_candidates expected WHERE expected.campaign_id=c.id AND expected.candidate_key=actual.candidate_key)) THEN RAISE EXCEPTION 'shadow campaign day graph does not reconstruct';END IF;
 END IF;RETURN NULL;
END;$$ LANGUAGE plpgsql;
DO $$DECLARE n TEXT;BEGIN FOREACH n IN ARRAY ARRAY['shadow_campaigns','shadow_campaign_candidates','shadow_campaign_days','shadow_campaign_day_candidates'] LOOP EXECUTE format('CREATE TRIGGER %I BEFORE UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION reject_shadow_campaign_mutation()','trg_'||n||'_immutable',n);END LOOP;END$$;
CREATE CONSTRAINT TRIGGER trg_shadow_campaign AFTER INSERT ON shadow_campaigns DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION validate_shadow_campaign_graph();
CREATE CONSTRAINT TRIGGER trg_shadow_candidate AFTER INSERT ON shadow_campaign_candidates DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION validate_shadow_campaign_graph();
CREATE CONSTRAINT TRIGGER trg_shadow_day AFTER INSERT ON shadow_campaign_days DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION validate_shadow_campaign_graph();
CREATE CONSTRAINT TRIGGER trg_shadow_day_candidate AFTER INSERT ON shadow_campaign_day_candidates DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION validate_shadow_campaign_graph();
CREATE INDEX idx_shadow_campaign_days_campaign ON shadow_campaign_days(campaign_id,sequence);
