-- OVR-607 additive operator evidence. No notification, acknowledgement,
-- incident mutation, risk, scheduling, promotion, or execution authority.

CREATE TABLE daily_operator_briefs(
 id UUID PRIMARY KEY,schema_name TEXT NOT NULL CHECK(schema_name='daily-operator-brief-v1'),operating_day DATE NOT NULL,timezone TEXT NOT NULL CHECK(timezone<>''),generated_at TIMESTAMPTZ NOT NULL CHECK(generated_at=date_trunc('microseconds',generated_at)),
 supervisor_id UUID NOT NULL REFERENCES daily_supervisor_assessments(id),supervisor_sha256 TEXT NOT NULL CHECK(supervisor_sha256~'^[0-9a-f]{64}$'),reconciliation_id UUID NOT NULL REFERENCES venue_reconciliation_runs(id),reconciliation_sha256 TEXT NOT NULL CHECK(reconciliation_sha256~'^[0-9a-f]{64}$'),
 cost_report_id UUID NOT NULL REFERENCES full_cost_attribution_reports(id),cost_report_sha256 TEXT NOT NULL CHECK(cost_report_sha256~'^[0-9a-f]{64}$'),review_summary_id UUID NOT NULL REFERENCES evidence_review_summaries(id),review_summary_sha256 TEXT NOT NULL CHECK(review_summary_sha256~'^[0-9a-f]{64}$'),
 performance_evaluation_id UUID REFERENCES trade_portfolio_evaluations(id),performance_evaluation_sha256 TEXT NOT NULL DEFAULT '' CHECK(performance_evaluation_sha256='' OR performance_evaluation_sha256~'^[0-9a-f]{64}$'),section_count INT NOT NULL CHECK(section_count=5),incident_count INT NOT NULL CHECK(incident_count BETWEEN 0 AND 512),sha256 TEXT NOT NULL CHECK(sha256~'^[0-9a-f]{64}$'),canonical_bytes BYTEA NOT NULL,canonical_json JSONB NOT NULL CHECK(jsonb_typeof(canonical_json)='object'),created_at TIMESTAMPTZ NOT NULL DEFAULT date_trunc('microseconds',clock_timestamp()),
 UNIQUE(operating_day,timezone),CHECK((performance_evaluation_id IS NULL)=(performance_evaluation_sha256='')),CHECK(sha256=encode(digest(canonical_bytes,'sha256'),'hex')),CHECK(canonical_json=convert_from(canonical_bytes,'UTF8')::JSONB),CHECK(canonical_json->>'schema'=schema_name),CHECK(canonical_json->>'operating_day'=operating_day::TEXT AND canonical_json->>'timezone'=timezone),CHECK(canonical_json->>'generated_at'=to_char(generated_at AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"')),CHECK(id=economic_deterministic_uuid('daily-operator-brief',schema_name||'@sha256:'||sha256))
);
CREATE TABLE daily_operator_brief_sections(brief_id UUID NOT NULL REFERENCES daily_operator_briefs(id),sequence INT NOT NULL CHECK(sequence BETWEEN 0 AND 4),section_name TEXT NOT NULL CHECK(section_name IN('performance','decisions','drift','risk','costs')),section_status TEXT NOT NULL,headline TEXT NOT NULL,explanation TEXT NOT NULL,evidence_kind TEXT NOT NULL,evidence_id UUID,evidence_sha256 TEXT NOT NULL,canonical_row JSONB NOT NULL CHECK(jsonb_typeof(canonical_row)='object'),PRIMARY KEY(brief_id,sequence),UNIQUE(brief_id,section_name));
CREATE TABLE daily_operator_brief_facts(brief_id UUID NOT NULL,section_sequence INT NOT NULL,sequence INT NOT NULL CHECK(sequence BETWEEN 0 AND 63),fact_key TEXT NOT NULL,fact_value TEXT NOT NULL,canonical_row JSONB NOT NULL CHECK(jsonb_typeof(canonical_row)='object'),PRIMARY KEY(brief_id,section_sequence,sequence),UNIQUE(brief_id,section_sequence,fact_key),FOREIGN KEY(brief_id,section_sequence) REFERENCES daily_operator_brief_sections(brief_id,sequence));
CREATE TABLE daily_operator_brief_incidents(brief_id UUID NOT NULL REFERENCES daily_operator_briefs(id),sequence INT NOT NULL CHECK(sequence BETWEEN 0 AND 511),incident_key TEXT NOT NULL,severity TEXT NOT NULL CHECK(severity IN('high','critical')),incident_state TEXT NOT NULL CHECK(incident_state='open'),source_kind TEXT NOT NULL,source_id UUID,source_sha256 TEXT NOT NULL,summary TEXT NOT NULL,required_action TEXT NOT NULL,canonical_row JSONB NOT NULL CHECK(jsonb_typeof(canonical_row)='object'),PRIMARY KEY(brief_id,sequence),UNIQUE(brief_id,incident_key));

CREATE FUNCTION reject_daily_operator_brief_mutation() RETURNS TRIGGER AS $$BEGIN RAISE EXCEPTION 'daily operator brief evidence is append-only';END;$$ LANGUAGE plpgsql;
CREATE FUNCTION validate_daily_operator_brief_graph() RETURNS TRIGGER AS $$
DECLARE target UUID;brief daily_operator_briefs%ROWTYPE;expected_incidents INT;
BEGIN
 IF TG_TABLE_NAME='daily_operator_briefs' THEN target:=NEW.id;ELSE target:=NEW.brief_id;END IF;SELECT * INTO brief FROM daily_operator_briefs WHERE id=target;IF brief.id IS NULL THEN RAISE EXCEPTION 'daily operator brief is missing';END IF;
 PERFORM 1 FROM daily_supervisor_assessments s JOIN venue_reconciliation_runs r ON r.id=s.reconciliation_id JOIN full_cost_attribution_reports c ON c.id=brief.cost_report_id JOIN evidence_review_summaries summary ON summary.id=c.summary_id WHERE s.id=brief.supervisor_id AND s.sha256=brief.supervisor_sha256 AND s.operating_day=brief.operating_day AND s.timezone=brief.timezone AND r.id=brief.reconciliation_id AND r.sha256=brief.reconciliation_sha256 AND c.sha256=brief.cost_report_sha256 AND summary.id=brief.review_summary_id AND summary.sha256=brief.review_summary_sha256;
 IF NOT FOUND THEN RAISE EXCEPTION 'daily operator brief parent evidence does not match';END IF;
 IF brief.performance_evaluation_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM trade_portfolio_evaluations e WHERE e.id=brief.performance_evaluation_id AND e.sha256=brief.performance_evaluation_sha256) THEN RAISE EXCEPTION 'daily operator brief performance evidence does not match';END IF;
 IF brief.section_count<>(SELECT count(*) FROM daily_operator_brief_sections WHERE brief_id=brief.id) OR brief.incident_count<>(SELECT count(*) FROM daily_operator_brief_incidents WHERE brief_id=brief.id) OR brief.canonical_json->'sections'<>(SELECT COALESCE(jsonb_agg(s.canonical_row ORDER BY s.sequence),'[]'::JSONB) FROM daily_operator_brief_sections s WHERE s.brief_id=brief.id) OR brief.canonical_json->'incidents'<>(SELECT COALESCE(jsonb_agg(i.canonical_row ORDER BY i.sequence),'[]'::JSONB) FROM daily_operator_brief_incidents i WHERE i.brief_id=brief.id) OR EXISTS(SELECT 1 FROM daily_operator_brief_sections s WHERE s.brief_id=brief.id AND s.canonical_row->'facts'<>(SELECT COALESCE(jsonb_agg(f.canonical_row ORDER BY f.sequence),'[]'::JSONB) FROM daily_operator_brief_facts f WHERE f.brief_id=s.brief_id AND f.section_sequence=s.sequence)) THEN RAISE EXCEPTION 'daily operator brief graph does not reconstruct';END IF;
 IF brief.canonical_json->>'supervisor_id'<>brief.supervisor_id::TEXT OR brief.canonical_json->>'supervisor_sha256'<>brief.supervisor_sha256 OR brief.canonical_json->>'reconciliation_id'<>brief.reconciliation_id::TEXT OR brief.canonical_json->>'reconciliation_sha256'<>brief.reconciliation_sha256 OR brief.canonical_json->>'cost_report_id'<>brief.cost_report_id::TEXT OR brief.canonical_json->>'cost_report_sha256'<>brief.cost_report_sha256 OR brief.canonical_json->>'review_summary_id'<>brief.review_summary_id::TEXT OR brief.canonical_json->>'review_summary_sha256'<>brief.review_summary_sha256 OR COALESCE(brief.canonical_json->>'performance_evaluation_id','')<>COALESCE(brief.performance_evaluation_id::TEXT,'') OR brief.canonical_json->>'performance_evaluation_sha256'<>brief.performance_evaluation_sha256 THEN RAISE EXCEPTION 'daily operator brief envelope does not reconstruct';END IF;
 SELECT (SELECT count(*) FROM daily_supervisor_attention WHERE assessment_id=brief.supervisor_id)+(SELECT count(*) FROM daily_supervisor_actions WHERE assessment_id=brief.supervisor_id AND admission='halted')+(SELECT count(*) FROM full_cost_attribution_lines WHERE report_id=brief.cost_report_id AND knowledge_status='unknown')+CASE WHEN brief.performance_evaluation_id IS NULL OR brief.canonical_json->'sections'->0->>'status'='negative' THEN 1 ELSE 0 END INTO expected_incidents;
 IF brief.incident_count<>expected_incidents OR EXISTS(SELECT 1 FROM daily_supervisor_attention a WHERE a.assessment_id=brief.supervisor_id AND NOT EXISTS(SELECT 1 FROM daily_operator_brief_incidents i WHERE i.brief_id=brief.id AND i.incident_key='supervisor_check:'||a.check_name AND i.incident_state='open' AND i.source_id=brief.supervisor_id)) OR EXISTS(SELECT 1 FROM daily_supervisor_actions a WHERE a.assessment_id=brief.supervisor_id AND a.admission='halted' AND NOT EXISTS(SELECT 1 FROM daily_operator_brief_incidents i WHERE i.brief_id=brief.id AND i.incident_key='work_halted:'||a.work_class AND i.incident_state='open')) OR EXISTS(SELECT 1 FROM full_cost_attribution_lines l WHERE l.report_id=brief.cost_report_id AND l.knowledge_status='unknown' AND NOT EXISTS(SELECT 1 FROM daily_operator_brief_incidents i WHERE i.brief_id=brief.id AND i.incident_key='cost_unknown:'||l.line_key AND i.incident_state='open')) THEN RAISE EXCEPTION 'daily operator brief incidents do not reconstruct';END IF;
 RETURN NULL;
END;$$ LANGUAGE plpgsql;
DO $$DECLARE table_name TEXT;BEGIN FOREACH table_name IN ARRAY ARRAY['daily_operator_briefs','daily_operator_brief_sections','daily_operator_brief_facts','daily_operator_brief_incidents'] LOOP EXECUTE format('CREATE TRIGGER %I BEFORE UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION reject_daily_operator_brief_mutation()','trg_'||table_name||'_immutable',table_name);END LOOP;END$$;
CREATE CONSTRAINT TRIGGER trg_daily_operator_brief AFTER INSERT ON daily_operator_briefs DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION validate_daily_operator_brief_graph();CREATE CONSTRAINT TRIGGER trg_daily_operator_section AFTER INSERT ON daily_operator_brief_sections DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION validate_daily_operator_brief_graph();CREATE CONSTRAINT TRIGGER trg_daily_operator_fact AFTER INSERT ON daily_operator_brief_facts DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION validate_daily_operator_brief_graph();CREATE CONSTRAINT TRIGGER trg_daily_operator_incident AFTER INSERT ON daily_operator_brief_incidents DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION validate_daily_operator_brief_graph();
CREATE INDEX idx_daily_operator_incidents_open ON daily_operator_brief_incidents(severity,incident_key,brief_id);
